### ISSUE TITLE
Conflict of NetFramework 4.6.1 and NetStandard 2.0

### ISSUE THREAD

**Issue by Geotsv** [SimonSimCity/Xamarin-CrossDownloadManager#107] opened 2019-03-10 06:57 UTC
Warning	NU1701	Package 'Xam.Plugins.DownloadManager 1.4.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	

Task Run and nothing happened ... no Status or nothing... Suspect was the above reason?

**Comment by SimonSimCity** [comment] 2019-03-11 17:28
Closing as duplicate of https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/issues/75

**Closed as completed by SimonSimCity** 2019-03-11 17:28 UTC
