### ISSUE TITLE
How to download backgrounding with Post method have payload

### ISSUE THREAD

**Issue by tangkhaiphuong** [SimonSimCity/Xamarin-CrossDownloadManager#90] opened 2018-06-14 09:10 UTC
The backend server support downloads a file by Post method with the payload. So how can do with CrossDownloadManager?

### Configuration

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] UWP
- [ ] Other

**Device:** 
- [ ] Simulator
- [x] Real device (please specify)

**Comment by SimonSimCity** [comment] 2018-06-14 11:05
It is true that the native download manager of iOS supports this feature, but at least for Android it would require quite a massive change since the native download manager there doesn't (see: https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/issues/29). Luckily we have the option there to write our own custom background process, which has been added as issue and researched, but not started yet (https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/issues/34).

I won't take initiative here because I don't need this feature yet. Everyone is very much welcome to start working on it and I'll feed him with as much information as I have as of today.

I'll close this issue as a duplicate of https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/issues/29.

**Closed by SimonSimCity** 2018-06-14 11:05 UTC

**Comment by SimonSimCity** [comment] 2018-06-14 11:07
As I wrote in #29, if you only want to have it on iOS and can update this plugin to support this feature on iOS only, I'd be happy to merge it, as long as you have it as a platform dependent feature until it's implemented also on Android and UWP.
