### ISSUE TITLE
Unable to instantiate receiver DownloadCompletedBroadcastReceiver

### ISSUE THREAD

**Issue by SatyaRamprasad** [SimonSimCity/Xamarin-CrossDownloadManager#74] opened 2018-01-05 10:11 UTC
Unhandled Exception:
```csharp
Java.Lang.RuntimeException: Unable to instantiate receiver md5122601985fa14a9be911c91910019277.DownloadCompletedBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "md5122601985fa14a9be911c91910019277.DownloadCompletedBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.pmr.PMR-1/base.apk"],nativeLibraryDirectories=[/data/app/com.pmr.PMR-1/lib/x86, /data/app/com.pmr.PMR-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
```

This is my InitDownloadManager (PCL Android)
```csharp
        void InitDownloadManager()
        {
            CrossDownloadManager.Current.PathNameForDownloadedFile = new Func<IDownloadFile, string>(file =>
            {
                string fileName = Android.Net.Uri.Parse(file.Url).Path.Split('/').Last();
                return Path.Combine(ApplicationContext.GetExternalFilesDir(Android.OS.Environment.DirectoryDownloads).AbsolutePath, fileName);
            });
            (CrossDownloadManager.Current as DownloadManagerImplementation).IsVisibleInDownloadsUi = true;
            (CrossDownloadManager.Current as DownloadManagerImplementation).NotificationVisibility = DownloadVisibility.VisibleNotifyCompleted;
        }
```
I have created an interface to send url in CrossDownloadmanager
```csharp
    public class FileDownloader : IFileDownloader 
    {
        public async Task DownloadFile(string url)
        {
            var foo = new Downloader();
            foo.InitializeDownload(url);
            foo.File.PropertyChanged += (sender, e) =>
            {
            };
            foo.StartDownloading(true);
        }
    }
```
After Downloading the File it throws the above Exception.
Help me on this.
Thanks In Advance @SimonSimCity @martijn00  @fela98  @BtrJay

**Comment by SatyaRamprasad** [comment] 2018-01-11 07:29
Any Solution?
Thanks In Advance @SimonSimCity @martijn00 @fela98 @BtrJay

**Comment by SimonSimCity** [comment] 2018-01-16 05:38
Please don't link these issues to everyone. Most of these people you listed here are not anymore working on this project and you'll just keep annoying them.

I am myself not working with this project anymore and are about to hand it over to someone.

Can you please tell me what other investigations you've done to nail down the problem? F.e. do you get this exception every time? Which version of Android have you tested this with? Have you tested the sample project? Does it work/fail? I just guess it's only on Android since you haven't written anything about iOS here ...

**Comment by SatyaRamprasad** [comment] 2018-01-18 13:08
@SimonSimCity 

Yes, i am  getting this exception every time when the download completes and android version is 7.
It is working fine in emulators.

**Comment by SimonSimCity** [comment] 2018-02-19 06:55
@SatyaRamprasad Can you please clarify if this happens in the simulator or also on a real device? If it's on a real device, please include the manufacturer and model number so I can track it down and try it further.

I haven't had much luck reproducing it until now ...

**Comment by SatyaRamprasad** [comment] 2018-02-19 14:32
@SimonSimCity  In emulators, downloads are working where as in real devices like Lenovo Z2plus(android version is 7) , Redmi  4A (android version is 6) app is crashing.

**Comment by SimonSimCity** [comment] 2018-02-24 15:44
@SatyaRamprasad I've now tried it on a Nexus 5x and it worked beautifully. The only difference I noticed was that I had to add the permission `android.permission.INTERNET` when compiling in `Release` mode, but this could well be due to the code I wrote.

What error do you get? If your app is crashing, there must also be a crash report, latest if you use the `Device Monitor`. Please post the exception here you're facing there and also the rest of the report if it's connected to the exception you're facing.

**Comment by SimonSimCity** [comment] 2018-03-19 08:02
@SatyaRamprasad Do you still see your app crashing? If I don't answer within the next weeks and provide more info here I'm afraid I have to close this issue due to a lack of feedback and insight.

**Comment by SatyaRamprasad** [comment] 2018-03-19 08:38
Java.Lang.RuntimeException: Unable to instantiate receiver md5122601985fa14a9be911c91910019277.DownloadCompletedBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "md5122601985fa14a9be911c91910019277.DownloadCompletedBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.pmr.PMR-1/base.apk"],nativeLibraryDirectories=[/data/app/com.pmr.PMR-1/lib/x86, /data/app/com.pmr.PMR-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]



@SimonSimCity  this is the exception i am getting every time when i downloads.

**Comment by SimonSimCity** [comment] 2018-03-19 08:45
@SatyaRamprasad That's what I already know, and I can only reply that I've never seen this happening in one of my apps and need more info from you. A sample project where you get this would be great. I can't do anything with only this ...

If you want, I could also assist you in setting up the sample project and trying it out

If you don't provide me more data, I'm afraid I have to close this issue as `not reproducible` and `not enough details provided`.

**Closed** 2018-03-19 09:22 UTC
Labels: Android, feedback-needed
